name: videofi_mark2
description: Start a video call instantly.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  socket_io_client: ^1.0.2
  flutter_webrtc: ^0.8.5
  flutter_riverpod: ^1.0.3
  flutter_ringtone_player: ^3.2.0
  just_audio: ^0.9.24
  flutter_dotenv: ^5.0.2
  flutter_android_volume_keydown: ^1.0.0
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/
    - .env
